// This file is auto-generated by the script at src/scripts/generateImageImports.ts
// !!! DO NOT EDIT !!!
import img0 from '../../public/assets/images/commission/20210217_金沢.jpg'
import img1 from '../../public/assets/images/commission/20210316_朱耶式.jpg'
import img2 from '../../public/assets/images/commission/20210331_ALETH.jpg'
import img3 from '../../public/assets/images/commission/20210424_Laxy.jpg'
import img4 from '../../public/assets/images/commission/20210428_楠ハルイ.jpg'
import img5 from '../../public/assets/images/commission/20210516_四ノ宮しの.jpg'
import img6 from '../../public/assets/images/commission/20210523_ALETH.jpg'
import img7 from '../../public/assets/images/commission/20210525_のんびり.jpg'
import img8 from '../../public/assets/images/commission/20210531_Laxy.jpg'
import img9 from '../../public/assets/images/commission/20210708_四ノ宮しの.jpg'
import img10 from '../../public/assets/images/commission/20210815_のんびり.jpg'
import img11 from '../../public/assets/images/commission/20210902_四ノ宮しの.jpg'
import img12 from '../../public/assets/images/commission/20211018_Laxy.jpg'
import img13 from '../../public/assets/images/commission/20211018_四ノ宮しの.jpg'
import img14 from '../../public/assets/images/commission/20220113_Laxy.jpg'
import img15 from '../../public/assets/images/commission/20220321_四ノ宮しの.jpg'
import img16 from '../../public/assets/images/commission/20220403_雨音.jpg'
import img17 from '../../public/assets/images/commission/20220628_Laxy.jpg'
import img18 from '../../public/assets/images/commission/20221022_RENXZD.jpg'
import img19 from '../../public/assets/images/commission/20221030_RENXZD.jpg'
import img20 from '../../public/assets/images/commission/20230701_淵゛.jpg'
import img21 from '../../public/assets/images/commission/20230703_Lowrise.jpg'
import img22 from '../../public/assets/images/commission/20240211_hmng.jpg'
import img23 from '../../public/assets/images/commission/20240305_Lowrise.jpg'
import img24 from '../../public/assets/images/photography/20140327_memorial/0001.jpg'
import img25 from '../../public/assets/images/photography/20140327_memorial/0002.jpg'
import img26 from '../../public/assets/images/photography/20140327_memorial/0003.jpg'
import img27 from '../../public/assets/images/photography/20140327_memorial/0004.jpg'
import img28 from '../../public/assets/images/photography/20140327_memorial/0005.jpg'
import img29 from '../../public/assets/images/photography/20140327_memorial/0006.jpg'
import img30 from '../../public/assets/images/photography/20140327_memorial/0007.jpg'
import img31 from '../../public/assets/images/photography/20150209_blossom/0001.jpg'
import img32 from '../../public/assets/images/photography/20150209_blossom/0002.jpg'
import img33 from '../../public/assets/images/photography/20150209_blossom/0003.jpg'
import img34 from '../../public/assets/images/photography/20150209_blossom/0004.jpg'
import img35 from '../../public/assets/images/photography/20150209_blossom/0005.jpg'
import img36 from '../../public/assets/images/photography/20150209_blossom/0006.jpg'
import img37 from '../../public/assets/images/photography/20150209_blossom/0007.jpg'
import img38 from '../../public/assets/images/photography/20150209_blossom/0008.jpg'
import img39 from '../../public/assets/images/photography/20150209_blossom/0009.jpg'
import img40 from '../../public/assets/images/photography/20150329_regret/0001.jpg'
import img41 from '../../public/assets/images/photography/20150329_regret/0002.jpg'
import img42 from '../../public/assets/images/photography/20150329_regret/0003.jpg'
import img43 from '../../public/assets/images/photography/20150329_regret/0004.jpg'
import img44 from '../../public/assets/images/photography/20150329_regret/0005.jpg'
import img45 from '../../public/assets/images/photography/20150329_regret/0006.jpg'
import img46 from '../../public/assets/images/photography/20150329_regret/0007.jpg'
import img47 from '../../public/assets/images/photography/20150329_regret/0008.jpg'
import img48 from '../../public/assets/images/photography/20150329_regret/0009.jpg'
import img49 from '../../public/assets/images/photography/20150329_regret/0010.jpg'
import img50 from '../../public/assets/images/photography/20150726_refusal/0001.jpg'
import img51 from '../../public/assets/images/photography/20150726_refusal/0002.jpg'
import img52 from '../../public/assets/images/photography/20150726_refusal/0003.jpg'
import img53 from '../../public/assets/images/photography/20150726_refusal/0004.jpg'
import img54 from '../../public/assets/images/photography/20150726_refusal/0005.jpg'
import img55 from '../../public/assets/images/photography/20150726_refusal/0006.jpg'
import img56 from '../../public/assets/images/photography/20150726_refusal/0007.jpg'
import img57 from '../../public/assets/images/photography/20150809_funeral/0001.jpg'
import img58 from '../../public/assets/images/photography/20150809_funeral/0002.jpg'
import img59 from '../../public/assets/images/photography/20150809_funeral/0003.jpg'
import img60 from '../../public/assets/images/photography/20150809_funeral/0004.jpg'
import img61 from '../../public/assets/images/photography/20150809_funeral/0005.jpg'
import img62 from '../../public/assets/images/photography/20150809_funeral/0006.jpg'
import img63 from '../../public/assets/images/photography/20150809_funeral/0007.jpg'
import img64 from '../../public/assets/images/photography/20151125_awareness/0001.jpg'
import img65 from '../../public/assets/images/photography/20151125_awareness/0002.jpg'
import img66 from '../../public/assets/images/photography/20151125_awareness/0003.jpg'
import img67 from '../../public/assets/images/photography/20151125_awareness/0004.jpg'
import img68 from '../../public/assets/images/photography/20160505_origami/0001.jpg'
import img69 from '../../public/assets/images/photography/20160505_origami/0002.jpg'
import img70 from '../../public/assets/images/photography/20160715_unbalance/0001.jpg'
import img71 from '../../public/assets/images/photography/20160715_unbalance/0002.jpg'
import img72 from '../../public/assets/images/photography/20160715_unbalance/0003.jpg'
import img73 from '../../public/assets/images/photography/20160715_unbalance/0004.jpg'
import img74 from '../../public/assets/images/photography/20160715_unbalance/0005.jpg'
import img75 from '../../public/assets/images/photography/20160715_unbalance/0006.jpg'
import img76 from '../../public/assets/images/photography/20160715_unbalance/0007.jpg'
import img77 from '../../public/assets/images/photography/20160715_unbalance/0008.jpg'
import img78 from '../../public/assets/images/photography/20160715_unbalance/0009.jpg'
import img79 from '../../public/assets/images/photography/20170720_wander/0001.jpg'
import img80 from '../../public/assets/images/photography/20170720_wander/0002.jpg'
import img81 from '../../public/assets/images/photography/20170720_wander/0003.jpg'
import img82 from '../../public/assets/images/photography/20170720_wander/0004.jpg'
import img83 from '../../public/assets/images/photography/20170720_wander/0005.jpg'
import img84 from '../../public/assets/images/photography/20170720_wander/0006.jpg'
import img85 from '../../public/assets/images/photography/20170720_wander/0007.jpg'
import img86 from '../../public/assets/images/photography/20170720_wander/0008.jpg'
import img87 from '../../public/assets/images/photography/20170720_wander/0009.jpg'
import img88 from '../../public/assets/images/photography/20170720_wander/0010.jpg'
import img89 from '../../public/assets/images/photography/20170720_wander/0011.jpg'
import img90 from '../../public/assets/images/photography/20170720_wander/0012.jpg'
import img91 from '../../public/assets/images/photography/20170720_wander/0013.jpg'
import img92 from '../../public/assets/images/photography/20170720_wander/0014.jpg'
import img93 from '../../public/assets/images/photography/20170720_wander/0015.jpg'
import img94 from '../../public/assets/images/photography/20190214_dreamer/0001.jpg'
import img95 from '../../public/assets/images/photography/20190214_dreamer/0002.jpg'
import img96 from '../../public/assets/images/photography/20190214_dreamer/0003.jpg'
import img97 from '../../public/assets/images/photography/20190214_dreamer/0004.jpg'
import img98 from '../../public/assets/images/photography/20190214_dreamer/0005.jpg'
import img99 from '../../public/assets/images/photography/20190214_dreamer/0006.jpg'
import img100 from '../../public/assets/images/photography/awareness.jpg'
import img101 from '../../public/assets/images/photography/blossom.jpg'
import img102 from '../../public/assets/images/photography/dreamer.jpg'
import img103 from '../../public/assets/images/photography/funeral.jpg'
import img104 from '../../public/assets/images/photography/memorial.jpg'
import img105 from '../../public/assets/images/photography/origami.jpg'
import img106 from '../../public/assets/images/photography/refusal.jpg'
import img107 from '../../public/assets/images/photography/regret.jpg'
import img108 from '../../public/assets/images/photography/unbalance.jpg'
import img109 from '../../public/assets/images/photography/wander.jpg'

export const imageImports = {
  '20210217_金沢': img0,
  '20210316_朱耶式': img1,
  '20210331_ALETH': img2,
  '20210424_Laxy': img3,
  '20210428_楠ハルイ': img4,
  '20210516_四ノ宮しの': img5,
  '20210523_ALETH': img6,
  '20210525_のんびり': img7,
  '20210531_Laxy': img8,
  '20210708_四ノ宮しの': img9,
  '20210815_のんびり': img10,
  '20210902_四ノ宮しの': img11,
  '20211018_Laxy': img12,
  '20211018_四ノ宮しの': img13,
  '20220113_Laxy': img14,
  '20220321_四ノ宮しの': img15,
  '20220403_雨音': img16,
  '20220628_Laxy': img17,
  '20221022_RENXZD': img18,
  '20221030_RENXZD': img19,
  '20230701_淵゛': img20,
  '20230703_Lowrise': img21,
  '20240211_hmng': img22,
  '20240305_Lowrise': img23,
  '20140327_memorial_0001': img24,
  '20140327_memorial_0002': img25,
  '20140327_memorial_0003': img26,
  '20140327_memorial_0004': img27,
  '20140327_memorial_0005': img28,
  '20140327_memorial_0006': img29,
  '20140327_memorial_0007': img30,
  '20150209_blossom_0001': img31,
  '20150209_blossom_0002': img32,
  '20150209_blossom_0003': img33,
  '20150209_blossom_0004': img34,
  '20150209_blossom_0005': img35,
  '20150209_blossom_0006': img36,
  '20150209_blossom_0007': img37,
  '20150209_blossom_0008': img38,
  '20150209_blossom_0009': img39,
  '20150329_regret_0001': img40,
  '20150329_regret_0002': img41,
  '20150329_regret_0003': img42,
  '20150329_regret_0004': img43,
  '20150329_regret_0005': img44,
  '20150329_regret_0006': img45,
  '20150329_regret_0007': img46,
  '20150329_regret_0008': img47,
  '20150329_regret_0009': img48,
  '20150329_regret_0010': img49,
  '20150726_refusal_0001': img50,
  '20150726_refusal_0002': img51,
  '20150726_refusal_0003': img52,
  '20150726_refusal_0004': img53,
  '20150726_refusal_0005': img54,
  '20150726_refusal_0006': img55,
  '20150726_refusal_0007': img56,
  '20150809_funeral_0001': img57,
  '20150809_funeral_0002': img58,
  '20150809_funeral_0003': img59,
  '20150809_funeral_0004': img60,
  '20150809_funeral_0005': img61,
  '20150809_funeral_0006': img62,
  '20150809_funeral_0007': img63,
  '20151125_awareness_0001': img64,
  '20151125_awareness_0002': img65,
  '20151125_awareness_0003': img66,
  '20151125_awareness_0004': img67,
  '20160505_origami_0001': img68,
  '20160505_origami_0002': img69,
  '20160715_unbalance_0001': img70,
  '20160715_unbalance_0002': img71,
  '20160715_unbalance_0003': img72,
  '20160715_unbalance_0004': img73,
  '20160715_unbalance_0005': img74,
  '20160715_unbalance_0006': img75,
  '20160715_unbalance_0007': img76,
  '20160715_unbalance_0008': img77,
  '20160715_unbalance_0009': img78,
  '20170720_wander_0001': img79,
  '20170720_wander_0002': img80,
  '20170720_wander_0003': img81,
  '20170720_wander_0004': img82,
  '20170720_wander_0005': img83,
  '20170720_wander_0006': img84,
  '20170720_wander_0007': img85,
  '20170720_wander_0008': img86,
  '20170720_wander_0009': img87,
  '20170720_wander_0010': img88,
  '20170720_wander_0011': img89,
  '20170720_wander_0012': img90,
  '20170720_wander_0013': img91,
  '20170720_wander_0014': img92,
  '20170720_wander_0015': img93,
  '20190214_dreamer_0001': img94,
  '20190214_dreamer_0002': img95,
  '20190214_dreamer_0003': img96,
  '20190214_dreamer_0004': img97,
  '20190214_dreamer_0005': img98,
  '20190214_dreamer_0006': img99,
  'awareness': img100,
  'blossom': img101,
  'dreamer': img102,
  'funeral': img103,
  'memorial': img104,
  'origami': img105,
  'refusal': img106,
  'regret': img107,
  'unbalance': img108,
  'wander': img109,
} as const
